# Generated by Django 5.2 on 2025-04-18 11:38

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productimage_image_path_product_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path),
        ),
    ]
