# Generated by Django 5.2 on 2025-04-18 11:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Ұл'), ('F', 'Қыз')], default='M', max_length=1, verbose_name='Жыныс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vipclient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', unique=True, verbose_name='Телефон нөмірі'),
        ),
    ]
